/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SkillShopInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkPurchase"
      | "hasListingAccess"
      | "hasPurchased"
      | "listingFee"
      | "owner"
      | "payListingFee"
      | "purchase"
      | "skills"
      | "usdcToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ListingFeePaid" | "SkillPurchased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "checkPurchase",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasListingAccess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPurchased",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listingFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payListingFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchase",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "skills",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "usdcToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "checkPurchase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasListingAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPurchased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listingFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payListingFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "purchase", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "skills", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdcToken", data: BytesLike): Result;
}

export namespace ListingFeePaidEvent {
  export type InputTuple = [seller: AddressLike, price: BigNumberish];
  export type OutputTuple = [seller: string, price: bigint];
  export interface OutputObject {
    seller: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SkillPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    skillId: BigNumberish,
    price: BigNumberish
  ];
  export type OutputTuple = [buyer: string, skillId: bigint, price: bigint];
  export interface OutputObject {
    buyer: string;
    skillId: bigint;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SkillShop extends BaseContract {
  connect(runner?: ContractRunner | null): SkillShop;
  waitForDeployment(): Promise<this>;

  interface: SkillShopInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkPurchase: TypedContractMethod<
    [buyer: AddressLike, skillId: BigNumberish],
    [boolean],
    "view"
  >;

  hasListingAccess: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  hasPurchased: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  listingFee: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  payListingFee: TypedContractMethod<[], [void], "nonpayable">;

  purchase: TypedContractMethod<[skillId: BigNumberish], [void], "nonpayable">;

  skills: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean] & { id: bigint; price: bigint; active: boolean }
    ],
    "view"
  >;

  usdcToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkPurchase"
  ): TypedContractMethod<
    [buyer: AddressLike, skillId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasListingAccess"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasPurchased"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "listingFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payListingFee"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "purchase"
  ): TypedContractMethod<[skillId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "skills"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean] & { id: bigint; price: bigint; active: boolean }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "usdcToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ListingFeePaid"
  ): TypedContractEvent<
    ListingFeePaidEvent.InputTuple,
    ListingFeePaidEvent.OutputTuple,
    ListingFeePaidEvent.OutputObject
  >;
  getEvent(
    key: "SkillPurchased"
  ): TypedContractEvent<
    SkillPurchasedEvent.InputTuple,
    SkillPurchasedEvent.OutputTuple,
    SkillPurchasedEvent.OutputObject
  >;

  filters: {
    "ListingFeePaid(address,uint256)": TypedContractEvent<
      ListingFeePaidEvent.InputTuple,
      ListingFeePaidEvent.OutputTuple,
      ListingFeePaidEvent.OutputObject
    >;
    ListingFeePaid: TypedContractEvent<
      ListingFeePaidEvent.InputTuple,
      ListingFeePaidEvent.OutputTuple,
      ListingFeePaidEvent.OutputObject
    >;

    "SkillPurchased(address,uint256,uint256)": TypedContractEvent<
      SkillPurchasedEvent.InputTuple,
      SkillPurchasedEvent.OutputTuple,
      SkillPurchasedEvent.OutputObject
    >;
    SkillPurchased: TypedContractEvent<
      SkillPurchasedEvent.InputTuple,
      SkillPurchasedEvent.OutputTuple,
      SkillPurchasedEvent.OutputObject
    >;
  };
}
